#!/bin/bash

# USAGE
# ./deploy-new-arch <spack defined architecture>

existing_jobs=$(squeue -p building | wc -l)
if [ "$existing_jobs" -gt "1" ]; then
    echo "Operations under progress, unable to continue"
    exit 1
fi

NEW_ARCH=$1

if grep -Fxq "${NEW_ARCH}" spack-arch-list; then
    echo "This architecture is already deployed"
    exit 1
fi

# create space-delimited string of installed packages
old_IFS=$IFS
IFS=$'\n' read -d '' -r -a lines < spack-arch-list

IFS=$old_IFS
SPACK_PACKAGE_NAME="${lines[*]}"

# install packages on new arch
echo "Starting job for architecture $NEW_ARCH..."
sbatch --job-name="newarch-${NEW_ARCH}" --constraint=$NEW_ARCH --output=logs/newarch-$NEW_ARCH-%j.out --export=SPACK_PACKAGE_NAME=$SPACK_PACKAGE_NAME slurm-install-batch.sh

# add new arch to file, if not already there (shouldn't be from the first check)
grep -qxF '${NEW_ARCH}' spack-arch-list || echo '${NEW_ARCH}' >> spack-arch-list