#!/bin/bash

# USAGE
# ./remove-package <spack package spec>

existing_jobs=$(squeue -p building | wc -l)
if [ "$existing_jobs" -gt "1" ]; then
    echo "Operations under progress, unable to continue"
    exit 1
fi

SPACK_PACKAGE_NAME=$1

# uninstall all specs assicated with package name
spack uninstall -a $SPACK_PACKAGE_NAME
spack -y gc

# remove line from installed_packages
sed -i "/$SPACK_PACKAGE_NAME/d" ./installed_packages
